export const PATH = {
    LOGIN: '/',
    START: '/start',
    FORM_LOGIN: '/form-login',
    FORM_REGISTER: '/form-register',
    COMMON_QUESTIONS: '/common-questions',
    FAQS: '/faqs',
    SUPPORT: '/support',
    QUESTIONS_ABOUT_MODAL: '/questions-about-modal',
    HOME: '/home',
    EARN_POINTS: '/earn-points',
    REDEEM_COUPON: '/redeem-coupon',
    SUCCESS_REDEEM: '/success-redeem',
    CODE_VALIDATION: '/code-validation',
    LEVELS: '/levels',
}